#
# Copyright (C) 2005-2015 John.Lee IT Services.
# All rights reserved. Use is subject to license terms.
#

err.installLicenseFail=Certificate installation failed\!

err.verifyLicenseFail=Certificate verification failed\!

info.installLicenseSuccess=Certificate installation successful, certificate validity period: {0} - {1}

debug.verifyLicenseSuccess=Certificate verification passed, certificate validity period: {0} - {1}
