#
# Copyright (C) 2005-2015 John.Lee IT Services.
# All rights reserved. Use is subject to license terms.
#
err.getServerInfoFail=Failed to obtain server hardware information\! {0}

err.xmlDecodeFail=Failed to obtain server hardware information\! {0}
err.generateLicenseFail=Certificate generation failed: {0} Argument: [{1}]

warn.getMacByInetAddress=Failed to obtain Mac address\: {0}

exc.consumerTypeIsNull=Consumer type is null\!

exc.expiryTimeBeforeNow=The certificate expiration time cannot be earlier than the current time\!

exc.expiryTimeBeforeIssuedTime=The certificate effective time cannot be later than the certificate expiration time\!

exc.invalidIpAddress=The current server's IP is not within the authorized range\!

exc.invalidMacAddress=The current server's Mac address is not within the authorized range\!

exc.invalidCpuSerial=The CPU serial number of the current server is not within the authorized range\!

exc.invalidMainBoardSerial=The motherboard serial number of the current server is not within the authorized range\!
exc.notGetHardwareInfo=Unable to obtain server hardware information!
